# Generated by Django 3.2.12 on 2024-07-27 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('current_balance', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('amount_frozen', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('invitation_code', models.CharField(blank=True, max_length=20)),
                ('daily_orders', models.IntegerField(default=38)),
                ('commission_ratio', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('completed_orders', models.IntegerField(default=0)),
                ('commision_earned', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('layer_information', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='orders.layer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, default='avatars/funEmoji-1720771137510_44EkmhY.png', null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
