# Generated by Django 3.2.12 on 2024-08-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
