# Generated by Django 3.2.12 on 2024-09-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_payment_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='joining_invitation_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
