# Generated by Django 3.2.12 on 2024-09-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_joining_invitation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='joining_invitation_code',
        ),
    ]
