# Generated by Django 3.2.12 on 2024-09-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240727_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='invitation_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='joining_invitation_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
