# Generated by Django 3.2.12 on 2024-08-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FROZEN', 'Frozen'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
